INSERT into PRODUITS (LIBELLE, STOCK, PRIXINVENT) values ('Pommes', 25, 3)
INSERT into PRODUITS (LIBELLE, STOCK, PRIXINVENT) values ('Bananes', 4, 8)
INSERT into PRODUITS (LIBELLE, STOCK, PRIXINVENT) values ('Poires', 12, 6)
INSERT into PRODUITS (LIBELLE, STOCK, PRIXINVENT) values ('Fraises', 8, 14)
INSERT into FOURNISSEURS (NOM, VILLE) values ('Sodebo', 'Paris')
INSERT into FOURNISSEURS (NOM, VILLE) values ('Rougeline', 'Rouen')
INSERT into ACHETER values (1, 1, 20, 34)
INSERT into ACHETER values (1, 2, 12, 28)
INSERT into ACHETER values (1, 4, 6, 14)
INSERT into ACHETER values (2, 4, 6, 11)